#!/bin/bash
# Generate Self-Signed Certificate for Arasul Platform
# Used when Let's Encrypt is not available (offline/local development)

set -e

CERT_DIR="${1:-/arasul/config/traefik/certs}"
DOMAIN="${2:-arasul.local}"
VALIDITY_DAYS="${3:-3650}"  # 10 years

echo "🔐 Generating Self-Signed Certificate for Arasul Platform"
echo "   Domain: $DOMAIN"
echo "   Certificate directory: $CERT_DIR"
echo "   Validity: $VALIDITY_DAYS days (~$(($VALIDITY_DAYS/365)) years)"
echo ""

# Create certificate directory
mkdir -p "$CERT_DIR"
chmod 755 "$CERT_DIR"

# Certificate and key paths
CERT_FILE="$CERT_DIR/arasul.crt"
KEY_FILE="$CERT_DIR/arasul.key"

# Check if certificate already exists
if [ -f "$CERT_FILE" ] && [ -f "$KEY_FILE" ]; then
    echo "⚠️  Certificate already exists:"
    echo "   Certificate: $CERT_FILE"
    echo "   Key: $KEY_FILE"
    echo ""

    # Show certificate info
    echo "📋 Current certificate info:"
    openssl x509 -in "$CERT_FILE" -noout -subject -dates 2>/dev/null || echo "   (Cannot read certificate)"
    echo ""

    read -p "   Overwrite existing certificate? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted. Keeping existing certificate."
        exit 0
    fi
fi

# Generate private key (4096 bit RSA)
echo "📝 Generating 4096-bit RSA private key..."
openssl genrsa -out "$KEY_FILE" 4096 2>/dev/null

# Set strict permissions on private key
chmod 600 "$KEY_FILE"

# Create OpenSSL config for SAN (Subject Alternative Names)
CONFIG_FILE="/tmp/openssl_san_config_$$.cnf"
cat > "$CONFIG_FILE" <<EOF
[req]
default_bits = 4096
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = v3_req

[dn]
C = DE
ST = Bayern
L = Munich
O = Arasul Platform
OU = Edge AI Appliance
CN = $DOMAIN

[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = $DOMAIN
DNS.2 = *.$DOMAIN
DNS.3 = localhost
IP.1 = 127.0.0.1
IP.2 = 172.30.0.1
EOF

# Get local IP address (try multiple methods)
LOCAL_IP=""
if command -v hostname &> /dev/null; then
    LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
fi

if [ -n "$LOCAL_IP" ]; then
    echo "IP.3 = $LOCAL_IP" >> "$CONFIG_FILE"
fi

# Generate self-signed certificate
echo "📝 Generating self-signed certificate..."
openssl req -new -x509 \
    -key "$KEY_FILE" \
    -out "$CERT_FILE" \
    -days "$VALIDITY_DAYS" \
    -config "$CONFIG_FILE" \
    -extensions v3_req \
    2>/dev/null

# Set certificate permissions
chmod 644 "$CERT_FILE"

# Cleanup config file
rm -f "$CONFIG_FILE"

echo ""
echo "✅ Self-signed certificate created successfully!"
echo ""
echo "📁 Files created:"
echo "   Certificate: $CERT_FILE"
echo "   Private Key: $KEY_FILE"
echo ""
echo "🔒 Permissions:"
echo "   Certificate: $(ls -la "$CERT_FILE" | awk '{print $1, $3, $4}')"
echo "   Private Key: $(ls -la "$KEY_FILE" | awk '{print $1, $3, $4}')"
echo ""

# Display certificate information
echo "📋 Certificate information:"
openssl x509 -in "$CERT_FILE" -noout -text | grep -A 2 "Subject:"
openssl x509 -in "$CERT_FILE" -noout -text | grep -A 10 "Subject Alternative Name"
echo ""
echo "📅 Validity:"
openssl x509 -in "$CERT_FILE" -noout -dates
echo ""

# Create TLS configuration for Traefik
TLS_CONFIG="$CERT_DIR/../dynamic/tls.yml"
echo "📝 Creating Traefik TLS configuration..."

cat > "$TLS_CONFIG" <<EOF
# Traefik TLS Configuration - Self-Signed Certificate
# This file is auto-generated by generate_self_signed_cert.sh

tls:
  certificates:
    - certFile: /etc/traefik/certs/arasul.crt
      keyFile: /etc/traefik/certs/arasul.key
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/arasul.crt
        keyFile: /etc/traefik/certs/arasul.key

  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: false
EOF

echo "✅ TLS configuration created: $TLS_CONFIG"
echo ""

# Disable Let's Encrypt in traefik.yml (when using self-signed)
TRAEFIK_CONFIG="$CERT_DIR/../traefik.yml"
if [ -f "$TRAEFIK_CONFIG" ]; then
    echo "📝 Updating Traefik configuration to use self-signed certificate..."

    # Comment out httpChallenge line
    sed -i.backup 's/^      httpChallenge:$/      # httpChallenge: # Disabled for self-signed cert/' "$TRAEFIK_CONFIG" 2>/dev/null || \
    sed -i '' 's/^      httpChallenge:$/      # httpChallenge: # Disabled for self-signed cert/' "$TRAEFIK_CONFIG" 2>/dev/null || true

    sed -i.backup 's/^        entryPoint: web$/        # entryPoint: web # Disabled for self-signed cert/' "$TRAEFIK_CONFIG" 2>/dev/null || \
    sed -i '' 's/^        entryPoint: web$/        # entryPoint: web # Disabled for self-signed cert/' "$TRAEFIK_CONFIG" 2>/dev/null || true

    echo "✅ Traefik configuration updated (backup saved as traefik.yml.backup)"
fi

echo ""
echo "⚠️  IMPORTANT: Browser Security Warning"
echo "   Self-signed certificates will trigger a security warning in browsers."
echo "   This is NORMAL and EXPECTED for self-signed certificates."
echo ""
echo "   To accept the certificate:"
echo "   - Chrome/Edge: Click 'Advanced' → 'Proceed to arasul.local (unsafe)'"
echo "   - Firefox: Click 'Advanced' → 'Accept the Risk and Continue'"
echo "   - Safari: Click 'Show Details' → 'visit this website'"
echo ""
echo "   For production use, consider using Let's Encrypt instead."
echo ""

echo "Next steps:"
echo "  1. Restart Traefik: docker-compose restart reverse-proxy"
echo "  2. Access dashboard: https://$DOMAIN"
echo "  3. Accept browser security warning (self-signed certificate)"
echo ""
