#!/bin/bash
set -euo pipefail

# ARASUL SSH Hardening Script
# Secures SSH for production deployment on Jetson AGX Orin
#
# Usage: sudo ./harden-ssh.sh [--port PORT] [--no-fail2ban]
#
# Actions:
#   1. Backup current sshd_config
#   2. Disable password authentication (key-only)
#   3. Change SSH port (default: 2222)
#   4. Disable root login
#   5. Set MaxAuthTries to 3
#   6. Install and configure fail2ban
#   7. Set SSH warning banner

SSH_PORT="${1:-2222}"
INSTALL_FAIL2BAN=true

# Parse options
while [[ $# -gt 0 ]]; do
    case "$1" in
        --port)
            SSH_PORT="$2"
            shift 2
            ;;
        --no-fail2ban)
            INSTALL_FAIL2BAN=false
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# Check root
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root (sudo)"
    exit 1
fi

SSHD_CONFIG="/etc/ssh/sshd_config"
BACKUP_DIR="/etc/ssh/backup_$(date +%Y%m%d_%H%M%S)"

echo "=================================================="
echo "  ARASUL SSH Hardening"
echo "=================================================="
echo "  SSH Port:      $SSH_PORT"
echo "  Fail2ban:      $INSTALL_FAIL2BAN"
echo "=================================================="
echo ""

# 1. Backup current config
echo "[1/7] Backing up current SSH configuration..."
mkdir -p "$BACKUP_DIR"
cp "$SSHD_CONFIG" "$BACKUP_DIR/sshd_config.bak"
echo "  Backup saved to: $BACKUP_DIR/sshd_config.bak"

# 2. Check that at least one SSH key exists for a user
ARASUL_HOME="/home/arasul"
if [ ! -f "$ARASUL_HOME/.ssh/authorized_keys" ] || [ ! -s "$ARASUL_HOME/.ssh/authorized_keys" ]; then
    echo ""
    echo "WARNING: No SSH authorized_keys found for user 'arasul'!"
    echo "  You MUST add an SSH key before disabling password auth."
    echo "  Run: ssh-copy-id -p 22 arasul@<jetson-ip>"
    echo "  Then re-run this script."
    echo ""
    read -rp "Continue anyway? (y/N): " CONFIRM
    if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
        echo "Aborted."
        exit 1
    fi
fi

# 3. Apply SSH hardening
echo "[2/7] Disabling password authentication (key-only)..."
cat > /etc/ssh/sshd_config.d/99-arasul-hardening.conf << 'SSHEOF'
# ARASUL SSH Hardening Configuration
# Generated by scripts/harden-ssh.sh
# Do not edit manually - re-run the script instead

# Authentication
PasswordAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 30

# Disable unused auth methods
ChallengeResponseAuthentication no
KerberosAuthentication no
GSSAPIAuthentication no
UsePAM yes

# Security
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
PermitUserEnvironment no

# Only allow arasul user
AllowUsers arasul

# Logging
LogLevel VERBOSE
SyslogFacility AUTH
SSHEOF

echo "[3/7] Setting SSH port to $SSH_PORT..."
sed -i "s/^#\?Port .*/Port $SSH_PORT/" "$SSHD_CONFIG"
# Also add to hardening config
echo "" >> /etc/ssh/sshd_config.d/99-arasul-hardening.conf
echo "# Port" >> /etc/ssh/sshd_config.d/99-arasul-hardening.conf
echo "Port $SSH_PORT" >> /etc/ssh/sshd_config.d/99-arasul-hardening.conf

echo "[4/7] Setting PermitRootLogin no..."
echo "  (Already configured in hardening config)"

echo "[5/7] Setting MaxAuthTries 3..."
echo "  (Already configured in hardening config)"

# 5. SSH Banner
echo "[6/7] Creating SSH warning banner..."
cat > /etc/ssh/arasul_banner << 'BANNEREOF'
*********************************************************************
*                                                                   *
*   ARASUL AI Platform - Authorized Access Only                     *
*                                                                   *
*   This system is for authorized use only. All activities           *
*   are monitored and logged. Unauthorized access attempts           *
*   will be reported.                                                *
*                                                                   *
*********************************************************************
BANNEREOF

echo "Banner /etc/ssh/arasul_banner" >> /etc/ssh/sshd_config.d/99-arasul-hardening.conf

# 6. Fail2ban
if [ "$INSTALL_FAIL2BAN" = true ]; then
    echo "[7/7] Installing and configuring fail2ban..."

    if ! command -v fail2ban-client &> /dev/null; then
        apt-get update -qq && apt-get install -y -qq fail2ban
    fi

    cat > /etc/fail2ban/jail.d/arasul-ssh.conf << JAILEOF
[sshd]
enabled = true
port = $SSH_PORT
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600
ignoreip = 127.0.0.1/8 ::1 172.30.0.0/24
JAILEOF

    systemctl enable fail2ban
    systemctl restart fail2ban
    echo "  Fail2ban configured: 3 retries, 1h ban"
else
    echo "[7/7] Skipping fail2ban installation (--no-fail2ban)"
fi

# Validate config before restart
echo ""
echo "Validating SSH configuration..."
if sshd -t; then
    echo "  Configuration valid!"
    systemctl restart sshd
    echo "  SSH service restarted on port $SSH_PORT"
else
    echo "ERROR: SSH configuration invalid! Restoring backup..."
    cp "$BACKUP_DIR/sshd_config.bak" "$SSHD_CONFIG"
    rm -f /etc/ssh/sshd_config.d/99-arasul-hardening.conf
    echo "  Backup restored. Please check the configuration."
    exit 1
fi

echo ""
echo "=================================================="
echo "  SSH Hardening Complete"
echo "=================================================="
echo "  Port:             $SSH_PORT"
echo "  Password Auth:    DISABLED"
echo "  Root Login:       DISABLED"
echo "  Max Auth Tries:   3"
echo "  Fail2ban:         $([ "$INSTALL_FAIL2BAN" = true ] && echo 'ACTIVE' || echo 'SKIPPED')"
echo ""
echo "  IMPORTANT: Test SSH connection in a NEW terminal"
echo "  BEFORE closing this session:"
echo "    ssh -p $SSH_PORT arasul@<jetson-ip>"
echo "=================================================="
