import { chromium } from 'playwright';
const URL='https://localhost:8443';
const b=await chromium.launch({headless:true});
const c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:1600,height:1000}});
const p=await c.newPage();
p.on('console',m=>{const t=m.text(); if(/CORS|Access-Control|blocked|Refused|Failed/i.test(t)) console.log('KONSOLE:',t.slice(0,300));});
p.on('requestfailed',r=>{ if(r.url().includes('bruecke')) console.log('FEHLT:', r.method(), r.url(), r.failure()?.errorText); });
p.on('response', async r=>{ if(r.url().includes('bruecke')) {
  const h=await r.allHeaders();
  console.log('ANTWORT', r.request().method(), r.status(), 'ACAO=', h['access-control-allow-origin'], 'ACAH=', h['access-control-allow-headers'], 'CORP=', h['cross-origin-resource-policy']);
}});
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.fill('input[name="username"], input[type="text"]','admin');
await p.fill('input[type="password"]','2309');
await p.click('button[type="submit"]');
await p.waitForTimeout(4000);
await p.evaluate(()=>{try{localStorage.setItem('arasul-onboarding-seen-v1','1');}catch{}});
await p.goto(`${URL}/workspace`,{waitUntil:'domcontentloaded'});
await p.waitForTimeout(4000);
await p.locator('[aria-label="Beispiel-App"]').first().click();
await p.waitForTimeout(10000);
await b.close();
